[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y libgl1-mesa-glx libglib2.0-0 libsm6 libxrender1 libxext6"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "waitress-serve --host=0.0.0.0 --port=$PORT app:app"
